pkg/store/blobs.go

I ran into issues on windows where Rename on a blob would fail with:
The process cannot access the file because it is being used by another process.
So close the *.incomplete file before trying to rename it.

store: Fix blob rename on windows

---

pkg/distribution/client.go
pkg/distribution/client_test.go

Add defensive checks to the functional options in client.go:
- Add nil checks to WithLogger and WithTransport
- Add empty string checks to WithStoreRootPath and WithUserAgent
- Add tests to verify these checks work correctly

Add nil and empty string checks to With functions

---

pkg/distribution/client_test.go
pkg/distribution/errors.go
pkg/store/errors.go
pkg/store/store.go
pkg/store/store_test.go

Difference between `docker model rm <ref>` and `docker image rm <ref>:`
```
docker model rm lala      
Failed to remove model: removing lala failed with status 404 Not Found: not found
25-03-21 14:21:02 ~/.docker/models % docker image rm lala      
Error response from daemon: No such image: lala:latest
25-03-21 14:21:05 ~/.docker/models % docker model rm lala/lalal
Model lala/lalal removed successfully
25-03-21 14:21:08 ~/.docker/models % docker image rm lala/lalal
Error response from daemon: No such image: lala/lalal:latest
```
This PR `adds store.ErrModelNotFound` to notify when a model is not been found to be removed, and uses it as alias of 
`distribution.ErrModelNotFound`. 
In `model-cli` we would be able to check if the error is `distribution.ErrModelNotFound` and if so return "No …

docker model rm should behave like docker image rm when the model is not found

---

distribution/client_test.go
internal/store/index.go

Client returns `distribution.ErrNotFound` when `Tag` is called and source model is missing.

Tag returns ErrModelNotFound when model is missing

---

cmd/mdltool/main.go
distribution/client.go
distribution/client_test.go
distribution/ecr_test.go
distribution/gar_test.go
distribution/progress.go
distribution/progress_test.go
internal/store/model.go
internal/store/store.go

* `PushModel` accepts a `progressWriter` and writes JSON progress updates.
* Some refactoring of the progress reporting code (could still use further improvement).
* Removes buffering from updates channel to ensure success/error message follows progress updates.
* Requires the code that writes to the updates channel to close the channel when finished writing in order to:
* clearly indicate when updates are complete
* make `store.Write` behavior consistent with `remote.Write`

Push with progress

---

distribution/client_test.go
internal/store/index.go
internal/store/layout.go
internal/store/store.go
internal/store/store_test.go

If the entire models directory is deleted, proceed without erroring by recreating index file as needed (and ensure layout exists whenever index is written). This allows a full `rm -rf ~/.docker/models` to recover fro corruption, without restarting model runner. It should be noted that deleting individual files may still produce errors or bad results.
(also fixes flaky test)

Handle missing store dir

---

README.md
cmd/mdltool/main.go
distribution/client.go
distribution/client_test.go
distribution/delete_test.go
distribution/ecr_test.go
distribution/errors.go
distribution/gar_test.go
internal/store/store.go
internal/store/store_test.go

`DeleteModel` accepts a `force` argument and behaves similarly to `docker rmi --force`
* When there are multiple tags, if the model is deleted by ID, force is required or `distribution.ErrConflict` is returned.
* When there are multiple tags, if the model is deleted by tag, it is merely untagged without deleting the underlying model
* When model has one or zero tags, force is not required and the model is always fully deleted.

Force delete

---

distribution/progress.go
distribution/progress_test.go

Adds Total and Pulled fields to ProgressMessage struct to track the total bytes to transfer and bytes transferred so far.
This enables more detailed progress tracking and better UI feedback during model distribution operations.

Add total and pulled bytes to progress messages

---

scripts/model-push/push-model.sh

We usually don't need to push the latest tag, and including it by default is error-prone because it can overwrite the actual latest.
Moreover, since we repackage the artifact, the digest changes (we include the creation date in the config).

Do not push latest

---

scripts/model-push/llama-converter/Dockerfile
scripts/model-push/push-model.sh

Always build and utilize a local converter image based on the official upstream version. This change prepares for future updates to newer models that require an updated llama.cpp version.
Furthermore we avoid relying on privately hosted images.
This specific change now supports converting Qwen3 models.

Use local converter image for builds

---

internal/gguf/create.go
internal/gguf/metadata.go
internal/gguf/model_test.go
types/config.go

Includes GGUF metadata into config:
I considered these 3 options:
1. Ignore fields with more than X (50) elements: [example](https://oci.dag.dev/?blob=ignaciolopezluna020/gguf@sha256:dfb6cc6d0fdbf7323d9176fd2d0862c93003e434485346ec194f385b6c98212e&mt=application%2Fvnd.docker.ai.model.config.v0.1%2Bjson&size=1953&manifest=ignaciolopezluna020/gguf@sha256:307129b2aa40b5aa66dfc8b23310b2c20bb1ef4175b2edf95882a97ae8bc7bf5)
2. Show all fields: [example](https://oci.dag.dev/?blob=ignaciolopezluna020/gguf@sha256:977759ec4c5e088dc01897eed9a7de6fc02ed567939dbddab1b8a3a3a74c1994&mt=application%2Fvnd.docker.ai.model.config.v0.1%2Bjson&size=1133477&manifest=ignaciolopezluna020/gguf:all@sha256:8b58ae83af2e0253c02d3b051c852e8cc6fe1c7221240ce99e9220f2a855a066)
3. The gguf parser has this option …

Includes GGUF metadata into config

---

distribution/client.go
internal/store/store.go

`ResetStore` resets the client's `LocalStore` by fully removing the directory and reinitializing it.

client: Add ResetStore

---

distribution/client.go

In case of error reading store to list models, the model distribution will panic if there is a model without tag. This PR fixed that.

Do not assume a model always has a tag

---

.github/actions/package-model/action.yml

In composite actions, the working directory `context` is not automatically set to the directory where the action lives. Instead, it points to the calling workflow’s root, which doesn’t have a Dockerfile, hence [the error](https://github.com/docker/unsloth-dockerhub/actions/runs/15927307713/job/44933809958)

Fix context of GHA

---

README.md
builder/builder.go
cmd/mdltool/main.go
internal/mutate/model.go
internal/mutate/mutate.go
internal/mutate/mutate_test.go
types/config.go

Allows artifact producers to set the default context size when packaging an artifact.
* Adds optional `config.context_size` field to the model config JSON.
* Adds optional `--context-size` flag to the package command in `model-distribution-tool`
* Adds optional `WithContextSize` option to `*builder.Builder` SDK

Optionally set context size in artifact

---

cmd/mdltool/main.go
distribution/client.go
distribution/client_test.go
distribution/delete_test.go
distribution/ecr_test.go
distribution/gar_test.go

Return untagged tags on delete to make it more similar to `docker image rm`.
This PR combined with local changes in https://github.com/docker/model-runner and https://github.com/docker/model-cli:
```
$ docker model tag ai/smollm2 dorin/smollm2
Model "ai/smollm2" tagged successfully with "index.docker.io/dorin/smollm2:latest"
$ docker model inspect ai/smollm2
{
"id": "sha256:354bf30d0aa3af413d2aa5ae4f23c66d78980072d1e07a5b0d776e9606a2f0b9",
"tags": [
"ai/smollm2",
"index.docker.io/dorin/smollm2:latest"
],
$ docker model rm -f 354bf30d0aa3af413d2aa5ae4f23c66d78980072d1e07a5b0d776e9606a2f0b9
Untagged: ai/smollm2
Untagged: index.docker.io/dorin/smollm2:latest
Model sha256:354bf30d0aa3af413d2aa5ae4f23c66d78980072d1e07a5b0d776e9606a2f0b9 removed successfully
```

distribution client: return untagged tags on delete

---

distribution/client.go
distribution/delete_test.go
internal/store/index.go
internal/store/index_test.go
internal/store/store.go
internal/store/store_test.go

From https://github.com/docker/model-runner/pull/100#discussion_r2189603299.
Return structured response for untagged and deleted models.
https://github.com/docker/model-runner/pull/100 and https://github.com/docker/model-cli/pull/122 will require small changes once this PR is merged.
Without the required changes in the model-cli, this is the response I see:
```
$ MODEL_RUNNER_HOST=http://localhost:8080 docker model tag ai/smollm2 dorin/smollm2
Model "ai/smollm2" tagged successfully with "index.docker.io/dorin/smollm2:latest"
$ MODEL_RUNNER_HOST=http://localhost:8080 docker model inspect ai/smollm2
{
"id": "sha256:354bf30d0aa3af413d2aa5ae4f23c66d78980072d1e07a5b0d776e9606a2f0b9",
"tags": [
"ai/smollm2",
"index.docker.io/dorin/smollm2:latest"
],
"created": 1742816981,
"config": {
"format": …
```

distribution client: return structured response for untagged and deleted models

---

internal/store/index.go
internal/store/index_test.go
internal/store/store.go

Noticed in https://github.com/docker/model-distribution/pull/107#discussion_r2196764377.

store/index: return error from UnTag

---

.github/workflows/promote-model-to-production.yml

Crane supports copying all tags of a repository via `--all-tags` parameter, so we can skip the matrix strategy entirely

Simplify model promotion workflow

---

cmd/mdltool/main.go

Arguments are already parsed here: https://github.com/docker/model-distribution/blob/489d2c662c89361dd7c664140ee475e682721718/cmd/mdltool/main.go#L185

Fix: do not parse arguments twice

---

README.md
assets/template.jinja
builder/builder.go
builder/builder_test.go
cmd/mdltool/main.go
distribution/bundle_test.go
internal/bundle/bundle.go
internal/bundle/parse.go
internal/bundle/unpack.go
internal/partial/partial.go
internal/store/model.go
types/config.go
types/model.go

When model artifact has layer with media type `application/vnd.docker.ai.chat.template.jinja` unpack to file named `template.jinja` in runtime bundle.
To package models with custom chat templates use `WithChatTemplateFile` helper in `builder` package.

Allow configuration of chat template
